[package]
name = "gitai"
version = "0.1.0"
edition = "2024"


[dependencies]
async-trait = "0.1.77"
ast-grep-config = "0.21.2"
ast-grep-core = "0.21.2"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
streaming-iterator = "0.1.9"
tokio = { version = "1.45.0", features = ["full"] }
toml = "0.8.22"
futures = "0.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

thiserror = "2.0.12"
rayon = "1.10.0"
walkdir = "2.5.0"
zip = "4.2.0"
md5 = "0.8.0"
serde_yaml = "0.9.34"
num_cpus = "1.16.0"

[dev-dependencies]
tempfile = "3.20.0"
httpmock = "0.7.0"  # Using a recent version of httpmock
