# GitAI 配置文件示例
# 复制此文件到 ~/.config/gitai/config.toml 并根据需要修改

[ai]
# AI 服务 API 地址
api_url = "http://localhost:1234/v1/chat/completions"

# 使用的模型名称
model = "qwen2.5:32b"

# 温度参数 (0.0-1.0)
temperature = 0.7

# API 密钥 (可选，某些服务需要)
api_key = "your_api_key"

[scan]
# 默认扫描路径 (可选，未设置时使用当前目录)
default_path = "/path/to/your/project"

# 扫描超时时间（秒）
timeout = 300

# 并发任务数
jobs = 4

# 规则目录（可选）。未设置时使用 ~/.cache/gitai/rules
# rules_dir = "/home/you/.cache/gitai/rules"

# DevOps 平台配置 (可选)
# [devops]
# # 平台类型 (coding, github, gitlab)
# platform = "coding"
# 
# # API 基础URL
# base_url = "https://your-org.coding.net"
# 
# # 认证令牌
# token = "your_devops_token"
# 
# # 项目标识 (可选)
# project = "your-team/your-project"
# 
# # 超时时间（秒）
# timeout = 30
# 
# # 重试次数
# retry_count = 3