[ai]
api_url = "http://localhost:1234/v1/chat/completions"
model_name = "Qwen/Qwen3-32B-MLX-8bit"
temperature = 0.7
api_key = "YOUR_API_KEY_IF_NEEDED"

[tree_sitter]
# 是否启用语法树分析功能（默认关闭）
enabled = false
# 分析深度: "shallow", "medium", "deep"
analysis_depth = "medium"
# 是否启用缓存
cache_enabled = true
# 支持的语言列表
languages = ["rust", "javascript", "python", "go", "java"]

[account]
devops_platform = "coding"                    # Supported: "coding", "jira", "azure-devops"
base_url = "https://your-devops-instance.com" # Your DevOps instance URL
token = "YOUR_DEVOPS_API_TOKEN"               # Your personal access token
timeout = 30000                               # Optional: API request timeout in milliseconds (default: 30000)
retry_count = 3                               # Optional: API request retry count (default: 3)


[review]
auto_save = true
storage_path = "~/.gitai/review_results"
format = "markdown"
max_age_hours = 168
include_in_commit = true
