name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Show versions
        run: |
          rustc -Vv
          cargo -V

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (lint)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test (workspace)
        run: cargo test --workspace --all-targets --quiet

      - name: Test (workspace with all features)
        run: cargo test --workspace --all-features --all-targets --quiet

      - name: Test workspace integration
        run: cargo test --test workspace_integration_test --test core_functionality_test --quiet

      - name: Build: minimal/default/full
        run: |
          cargo build --workspace --no-default-features --features minimal
          cargo build --workspace --features default
          cargo build --workspace --features full

      - name: Verify workspace structure
        run: |
          echo "=== Verify workspace structure ==="
          # Check that all workspace members compile
          cargo check --workspace --all-targets
          # Check specific crates
          cargo check -p gitai-types
          cargo check -p gitai-core
          cargo check -p gitai-analysis
          cargo check -p gitai-cli
          cargo check -p gitai-mcp
          cargo check -p gitai-metrics
          cargo check -p gitai-security

