name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Show versions
        run: |
          rustc -Vv
          cargo -V

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (lint)
        run: cargo clippy --all-targets -- -D warnings

      - name: Test (default features)
        run: cargo test --all-targets --quiet

      - name: Test (all features)
        run: cargo test --all-features --all-targets --quiet

      - name: Build: minimal/default/full
        run: |
          cargo build --no-default-features --features minimal
          cargo build --features default
          cargo build --features full

